#!/system/bin/sh

# Welcome to the one and only original, universal
# SystemRW / SuperRW feat. MakeRW / ro2rw by lebigmac

# ==========================================================

#                 http://www.systemrw.com

# ==========================================================

app="sysrw"; author="lebigmac"; version="1.36"; title=$app"_"$version; appDir=`dirname $0`; binDir="$appDir/bin"; p="$binDir/superw"
[ ! -e $p ] && echo "Fatal error! Please reinstall program!" && exit -1
if [ `id -u` -eq 0 ]; then
  chmod +x $p; $p "$@";
else
  if ( which su &> /dev/null ); then su -c 'chmod +x $p; $p "$@";'; else echo "Error! Device is not rooted!"; exit -1; fi
fi

